services:
  - type: web
    name: pulse-portal-backend
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: pulse-portal-db-hrittika23-46ed.b.aivencloud.com
      - key: DB_PORT
        value: 14251
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL
        value: true
      - key: APP_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: database
      - key: BROADCAST_DRIVER
        value: pusher
      - key: PUSHER_APP_ID
        sync: false
      - key: PUSHER_APP_KEY
        sync: false
      - key: PUSHER_APP_SECRET
        sync: false
      - key: PUSHER_APP_CLUSTER
        sync: false
      - key: PUSHER_SCHEME
        value: https
      - key: PUSHER_PORT
        value: 443
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - fromGroup: pulse-portal-secrets

envVarGroups:
  - name: pulse-portal-secrets
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
